version: "3"
services:
  nginx:
    image: nginx-proxy:latest
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    ports:
      - "8080:8080"
    labels:
      kompose.image-pull-policy: IfNotPresent
    depends_on:
      - nodejs
    links:
      - nodejs
  nodejs:
    image: nodejs-react:latest
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    restart: always
    expose:
      - "3000"
    labels:
      kompose.image-pull-policy: IfNotPresent
